name: scrabble_word_checker
description: The Scrabble ODS Word Checker is a Flutter package that allows you to check if a word is in the Official Scrabble Dictionary (ODS).
version: 0.0.8
# author: TheBlackMan <paskasonga@gmail.com>
homepage: https://github.com/theblackman2/scrabble-word-checker

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.24.3

flutter: