name: scrabble_word_checker
description: Check words with the official scrabble dictionary.
version: 0.0.1
# author: TheBlackMan <paskasonga@gmail.com>
homepage: https://github.com/theblackman2/scrabble-word-checker

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.scrabble_word.checker
        pluginClass: ScrabbleWordChecker
      ios:
        pluginClass: ScrabbleWordChecker
      macos:
        pluginClass: ScrabbleWordChecker
      web:
        pluginClass: ScrabbleWordChecker
        filename: scrabble_word_checker.dart
      windows:
        pluginClass: ScrabbleWordChecker