name: scrabble_word_checker
description: Check words with the official scrabble dictionary.
version: 0.0.4
# author: TheBlackMan <paskasonga@gmail.com>
homepage: https://github.com/theblackman2/scrabble-word-checker

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: